/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DiscoveriesRouteImport } from './routes/discoveries'
import { Route as ConjectureRouteImport } from './routes/conjecture'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TheoremIdRouteImport } from './routes/theorem.$id'
import { Route as SearchConceptRouteImport } from './routes/search.concept'
import { Route as ResearchIdRouteImport } from './routes/research.$id'
import { Route as ContributorsIdRouteImport } from './routes/contributors.$id'
import { Route as ConjectureIdRouteImport } from './routes/conjecture.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSteeringRouteImport } from './routes/admin.steering'
import { Route as AdminCorpusRouteImport } from './routes/admin.corpus'
import { Route as AdminBulkRouteImport } from './routes/admin.bulk'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveriesRoute = DiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => rootRouteImport,
} as any)
const ConjectureRoute = ConjectureRouteImport.update({
  id: '/conjecture',
  path: '/conjecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TheoremIdRoute = TheoremIdRouteImport.update({
  id: '/theorem/$id',
  path: '/theorem/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchConceptRoute = SearchConceptRouteImport.update({
  id: '/concept',
  path: '/concept',
  getParentRoute: () => SearchRoute,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResearchRoute,
} as any)
const ContributorsIdRoute = ContributorsIdRouteImport.update({
  id: '/contributors/$id',
  path: '/contributors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConjectureIdRoute = ConjectureIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConjectureRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSteeringRoute = AdminSteeringRouteImport.update({
  id: '/steering',
  path: '/steering',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCorpusRoute = AdminCorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkRoute = AdminBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-docs': typeof ApiDocsRoute
  '/api-keys': typeof ApiKeysRoute
  '/browse': typeof BrowseRoute
  '/conjecture': typeof ConjectureRouteWithChildren
  '/discoveries': typeof DiscoveriesRoute
  '/jobs': typeof JobsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRouteWithChildren
  '/search': typeof SearchRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/sponsor': typeof SponsorRoute
  '/workers': typeof WorkersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bulk': typeof AdminBulkRoute
  '/admin/corpus': typeof AdminCorpusRoute
  '/admin/steering': typeof AdminSteeringRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/conjecture/$id': typeof ConjectureIdRoute
  '/contributors/$id': typeof ContributorsIdRoute
  '/research/$id': typeof ResearchIdRoute
  '/search/concept': typeof SearchConceptRoute
  '/theorem/$id': typeof TheoremIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/api-keys': typeof ApiKeysRoute
  '/browse': typeof BrowseRoute
  '/conjecture': typeof ConjectureRouteWithChildren
  '/discoveries': typeof DiscoveriesRoute
  '/jobs': typeof JobsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRouteWithChildren
  '/search': typeof SearchRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/sponsor': typeof SponsorRoute
  '/workers': typeof WorkersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bulk': typeof AdminBulkRoute
  '/admin/corpus': typeof AdminCorpusRoute
  '/admin/steering': typeof AdminSteeringRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/conjecture/$id': typeof ConjectureIdRoute
  '/contributors/$id': typeof ContributorsIdRoute
  '/research/$id': typeof ResearchIdRoute
  '/search/concept': typeof SearchConceptRoute
  '/theorem/$id': typeof TheoremIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-docs': typeof ApiDocsRoute
  '/api-keys': typeof ApiKeysRoute
  '/browse': typeof BrowseRoute
  '/conjecture': typeof ConjectureRouteWithChildren
  '/discoveries': typeof DiscoveriesRoute
  '/jobs': typeof JobsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRouteWithChildren
  '/search': typeof SearchRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/sponsor': typeof SponsorRoute
  '/workers': typeof WorkersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bulk': typeof AdminBulkRoute
  '/admin/corpus': typeof AdminCorpusRoute
  '/admin/steering': typeof AdminSteeringRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/conjecture/$id': typeof ConjectureIdRoute
  '/contributors/$id': typeof ContributorsIdRoute
  '/research/$id': typeof ResearchIdRoute
  '/search/concept': typeof SearchConceptRoute
  '/theorem/$id': typeof TheoremIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-docs'
    | '/api-keys'
    | '/browse'
    | '/conjecture'
    | '/discoveries'
    | '/jobs'
    | '/leaderboard'
    | '/library'
    | '/pricing'
    | '/profile'
    | '/research'
    | '/search'
    | '/settings'
    | '/signin'
    | '/sponsor'
    | '/workers'
    | '/admin/audit'
    | '/admin/bulk'
    | '/admin/corpus'
    | '/admin/steering'
    | '/admin/users'
    | '/conjecture/$id'
    | '/contributors/$id'
    | '/research/$id'
    | '/search/concept'
    | '/theorem/$id'
    | '/admin/'
    | '/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/api-keys'
    | '/browse'
    | '/conjecture'
    | '/discoveries'
    | '/jobs'
    | '/leaderboard'
    | '/library'
    | '/pricing'
    | '/profile'
    | '/research'
    | '/search'
    | '/settings'
    | '/signin'
    | '/sponsor'
    | '/workers'
    | '/admin/audit'
    | '/admin/bulk'
    | '/admin/corpus'
    | '/admin/steering'
    | '/admin/users'
    | '/conjecture/$id'
    | '/contributors/$id'
    | '/research/$id'
    | '/search/concept'
    | '/theorem/$id'
    | '/admin'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-docs'
    | '/api-keys'
    | '/browse'
    | '/conjecture'
    | '/discoveries'
    | '/jobs'
    | '/leaderboard'
    | '/library'
    | '/pricing'
    | '/profile'
    | '/research'
    | '/search'
    | '/settings'
    | '/signin'
    | '/sponsor'
    | '/workers'
    | '/admin/audit'
    | '/admin/bulk'
    | '/admin/corpus'
    | '/admin/steering'
    | '/admin/users'
    | '/conjecture/$id'
    | '/contributors/$id'
    | '/research/$id'
    | '/search/concept'
    | '/theorem/$id'
    | '/admin/'
    | '/admin/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiDocsRoute: typeof ApiDocsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BrowseRoute: typeof BrowseRoute
  ConjectureRoute: typeof ConjectureRouteWithChildren
  DiscoveriesRoute: typeof DiscoveriesRoute
  JobsRoute: typeof JobsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LibraryRoute: typeof LibraryRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  SearchRoute: typeof SearchRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SponsorRoute: typeof SponsorRoute
  WorkersRoute: typeof WorkersRoute
  ContributorsIdRoute: typeof ContributorsIdRoute
  TheoremIdRoute: typeof TheoremIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discoveries': {
      id: '/discoveries'
      path: '/discoveries'
      fullPath: '/discoveries'
      preLoaderRoute: typeof DiscoveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conjecture': {
      id: '/conjecture'
      path: '/conjecture'
      fullPath: '/conjecture'
      preLoaderRoute: typeof ConjectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/theorem/$id': {
      id: '/theorem/$id'
      path: '/theorem/$id'
      fullPath: '/theorem/$id'
      preLoaderRoute: typeof TheoremIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/concept': {
      id: '/search/concept'
      path: '/concept'
      fullPath: '/search/concept'
      preLoaderRoute: typeof SearchConceptRouteImport
      parentRoute: typeof SearchRoute
    }
    '/research/$id': {
      id: '/research/$id'
      path: '/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/contributors/$id': {
      id: '/contributors/$id'
      path: '/contributors/$id'
      fullPath: '/contributors/$id'
      preLoaderRoute: typeof ContributorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conjecture/$id': {
      id: '/conjecture/$id'
      path: '/$id'
      fullPath: '/conjecture/$id'
      preLoaderRoute: typeof ConjectureIdRouteImport
      parentRoute: typeof ConjectureRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/steering': {
      id: '/admin/steering'
      path: '/steering'
      fullPath: '/admin/steering'
      preLoaderRoute: typeof AdminSteeringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/corpus': {
      id: '/admin/corpus'
      path: '/corpus'
      fullPath: '/admin/corpus'
      preLoaderRoute: typeof AdminCorpusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk': {
      id: '/admin/bulk'
      path: '/bulk'
      fullPath: '/admin/bulk'
      preLoaderRoute: typeof AdminBulkRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBulkRoute: typeof AdminBulkRoute
  AdminCorpusRoute: typeof AdminCorpusRoute
  AdminSteeringRoute: typeof AdminSteeringRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBulkRoute: AdminBulkRoute,
  AdminCorpusRoute: AdminCorpusRoute,
  AdminSteeringRoute: AdminSteeringRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ConjectureRouteChildren {
  ConjectureIdRoute: typeof ConjectureIdRoute
}

const ConjectureRouteChildren: ConjectureRouteChildren = {
  ConjectureIdRoute: ConjectureIdRoute,
}

const ConjectureRouteWithChildren = ConjectureRoute._addFileChildren(
  ConjectureRouteChildren,
)

interface ResearchRouteChildren {
  ResearchIdRoute: typeof ResearchIdRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchIdRoute: ResearchIdRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

interface SearchRouteChildren {
  SearchConceptRoute: typeof SearchConceptRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchConceptRoute: SearchConceptRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiDocsRoute: ApiDocsRoute,
  ApiKeysRoute: ApiKeysRoute,
  BrowseRoute: BrowseRoute,
  ConjectureRoute: ConjectureRouteWithChildren,
  DiscoveriesRoute: DiscoveriesRoute,
  JobsRoute: JobsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LibraryRoute: LibraryRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResearchRoute: ResearchRouteWithChildren,
  SearchRoute: SearchRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SponsorRoute: SponsorRoute,
  WorkersRoute: WorkersRoute,
  ContributorsIdRoute: ContributorsIdRoute,
  TheoremIdRoute: TheoremIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
