[package]
name = "nasrudin-ga"
version.workspace = true
edition.workspace = true

[dependencies]
nasrudin-core = { path = "../core" }
nasrudin-derive = { path = "../derive" }
nasrudin-lean-bridge = { path = "../lean-bridge" }
nasrudin-rocks = { path = "../rocks" }
nasrudin-embed = { path = "../embed", default-features = false }
rand = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
xxhash-rust = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
bloomfilter = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
hyperlocal = "0.9"
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["client", "client-legacy", "tokio", "http1"] }
http-body-util = "0.1"
bytes = { workspace = true }
url = "2"
thiserror = { workspace = true }
instant-distance = { workspace = true }
bincode = "1"
num_cpus = { workspace = true }
sysinfo = { workspace = true }

[dev-dependencies]
tempfile = "3"
