// One-sentence plain-English summary of a theorem statement.
//
// A visiting professor who doesn't read Lean (and may not even know what
// PhysLean is) cannot derive meaning from
//
//   (pi d v:Nat (pi v (@ v:Lorentz.Vector v:d) (-> (= (...causalCharacter
//                  v:v) ...timeLike) (< (...spatialPart v:v)² (timeComponent
//                  v:v)²))))
//
// — even after we render it as LaTeX. The math reads, but the meaning
// doesn't survive without prose. So we ship a short, curated lookup of
// the highest-traffic PhysLean / Mathlib identifiers and a templated
// fallback for the rest.
//
// The fallback intentionally produces a slightly-stilted line like
//
//   "For every n : ℕ and every v : Lorentz vector, …"
//
// rather than trying to be fluent — it's better to be obviously
// templated than to fake an authoritative-sounding summary that's
// subtly wrong.

import { leanToHumanTitle } from './humanTitle';

// Curated lookups: keys are the full Lean qualifier from
// origin_payload.Imported.source. Values are written as if the reader has
// a bachelor's in math/physics but has never opened a Lean file.
const CURATED: Record<string, string> = {
  'Lorentz.Vector.timelike_time_dominates_space':
    'If a Lorentz 4-vector is timelike (its causal character is timeLike), then its squared spatial part is strictly less than its squared time component. In other words, time wins the contest for timelike vectors — that’s what makes the worldline future-directed inside the light cone.',
  'PhysLean.FourTree.mem_iff_mem_toMultiset':
    'For any FourTree (a 4-tuple-indexed tree-shaped container PhysLean uses for symmetric tensor data), an element x is in the tree exactly when x is in the multiset built by `toMultiset`. The membership predicates of the two representations agree.',
  'Electromagnetism.ElectromagneticPotential.vectorPotential_differentiable_time':
    'The vector potential of the electromagnetic 4-potential is differentiable in the time coordinate. A regularity / smoothness lemma that downstream proofs (e.g. derivation of the electric field from A) rely on.',
  'Lorentz.ContrMod.toFin1dℝ.eq_1':
    'The defining equation for the 1-dimensional ContrMod-to-ℝⁿ map: applying `toFin1dℝ` is the same as applying the underlying equivalence-as-function.',
  'CliffordAlgebra.range_lift':
    'The range of the canonical lift from a quadratic-form module M into its Clifford algebra equals the algebra-image (the closure under multiplication generated by M).',
  'StandardModel.repU1_fundamentalSU2_commute':
    'The Standard-Model U(1) representation and the fundamental SU(2) representation commute on a Higgs-doublet element. This is the algebraic backbone of the electroweak group being U(1) × SU(2).',
  'PhysLean.physHermite_norm_cons':
    'The L²-norm-style integral identity for physicists’ Hermite polynomials: for any natural number n and real c, the squared integral against the Gaussian measure decomposes the way physicists expect.',
  'PhysLean.List.orderedInsert_eraseIdx_orderedInsertEquiv_zero':
    'Inserting an element into an ordered list and then erasing the index where it landed — at position zero of the ordered-insert equivalence — recovers the original list. A round-trip lemma.',
  'PhysLean.List.orderedInsertPos_drop':
    'Dropping the first `orderedInsertPos` elements of an ordered insert behaves predictably under list-erase.',
  'PhysLean.List.orderedInsertEquiv.eq_1':
    'The defining equation of `orderedInsertEquiv`: it factors through `Equiv.trans` with the standard insertion equivalence.',
  'Electromagnetism.ElectromagneticPotential.fieldStrengthMatrix_diag_eq_zero':
    'The diagonal entries of the electromagnetic field-strength matrix Fμμ vanish. F is antisymmetric, so its diagonal is zero — formally proved here.',
  'Electromagnetism.DistElectromagneticPotential.oneDimPointParticle.eq_1':
    'Defining equation for the one-dimensional point-particle distributional electromagnetic potential. Says how the distribution evaluates on test functions.',
  'PhysLean.FourTree.Leaf.uniqueMap4.eq_1':
    'A `uniqueMap4` over a singleton leaf reduces to applying the map to the element. The base-case rewrite rule for FourTree’s map operation.',
  'Fermion.altRightRightUnit.eq_1':
    'Defining equation of the altRight–right unit map in the Fermion category — fixes its value on the scaled generator.',
  'Lorentz.Vector.smul_basis':
    'A Lorentz boost Λ applied to a basis vector eμ expands as a sum over all directions ν of the Λ-matrix entries times eν. The standard "matrix acts on basis" identity, formalised.',
};

interface ProseOpts {
  /** Lean qualifier from origin_payload.Imported.source, if any. */
  importedFrom?: string | null;
  /** Domain enum string if available. */
  domain?: string | null;
}

export function statementToProse(canonical: string, opts: ProseOpts = {}): string | null {
  const imp = opts.importedFrom;
  if (imp) {
    const hit = CURATED[imp];
    if (hit) return hit;
  }

  // Templated fallback: derive a humanised title and emit a stilted but
  // informative gloss. We don't try to summarise the body of the statement
  // structurally — that path leads to confidently-wrong summaries. Instead
  // we tell the reader what the theorem is _named_ for, and let the
  // rendered LaTeX below carry the actual content.
  const title = leanToHumanTitle(imp ?? null);
  if (title) {
    const domain = opts.domain ?? null;
    if (domain) {
      return `Concerns ${title.toLowerCase()} — a result in ${domainLabel(domain)}. See the formal statement below for the precise quantifiers and conclusion.`;
    }
    return `Concerns ${title.toLowerCase()}. See the formal statement below for the precise quantifiers and conclusion.`;
  }

  // No qualifier and not curated — we have nothing trustworthy to say.
  // Returning null lets the page suppress the prose box entirely rather
  // than emit something hand-wavy.
  if (!canonical || !canonical.trim()) return null;
  return null;
}

function domainLabel(raw: string): string {
  // Avoid a circular import by inlining the few labels we use here. The
  // canonical mapping is in lib/domains.ts.
  switch (raw) {
    case 'PureMath':
      return 'pure mathematics';
    case 'ClassicalMechanics':
      return 'classical mechanics';
    case 'Electromagnetism':
      return 'electromagnetism';
    case 'SpecialRelativity':
      return 'special relativity';
    case 'GeneralRelativity':
      return 'general relativity';
    case 'QuantumMechanics':
      return 'quantum mechanics';
    case 'QuantumFieldTheory':
      return 'quantum field theory';
    case 'Thermodynamics':
      return 'thermodynamics';
    case 'StatisticalMechanics':
      return 'statistical mechanics';
    default:
      return raw.toLowerCase();
  }
}
