use nasrudin_core::{Domain, Expr, ProofTree};
use nasrudin_lean_bridge::export::{render_lean_file, ExportConfig, ExportableProof};

#[test]
fn test_render_lean_file_tactic_proof() {
    let proof = ExportableProof {
        name: "rest_energy_auto".into(),
        statement: Expr::BinOp(
            nasrudin_core::BinOp::Eq,
            Box::new(Expr::Var("E".into())),
            Box::new(Expr::BinOp(
                nasrudin_core::BinOp::Mul,
                Box::new(Expr::Var("m".into())),
                Box::new(Expr::BinOp(
                    nasrudin_core::BinOp::Pow,
                    Box::new(Expr::Const(nasrudin_core::PhysConst::SpeedOfLight)),
                    Box::new(Expr::Lit(2, 1)),
                )),
            )),
        ),
        proof: ProofTree::TacticProof {
            tactic: "have hmc : 0 ≤ m * c ^ 2 := mul_nonneg hm (le_of_lt c_pos)\n  have h_sqrt := congr_arg Real.sqrt h_em\n  rwa [Real.sqrt_sq hE, Real.sqrt_sq hmc] at h_sqrt".into(),
            proof_term: vec![],
        },
        description: "E = mc² from mass-shell at rest".into(),
        imports: vec![
            "PhysicsGenerator.Basic".into(),
            "PhysicsGenerator.Axioms.SpecialRelativity".into(),
        ],
        domain: Domain::SpecialRelativity,
        theorem_id: "abcdef0123456789".into(),
        tactic_used: Some("grind".into()),
    };

    let config = ExportConfig::default();
    let lean = render_lean_file(&proof, &config);

    assert!(lean.contains("import Mathlib"), "should import Mathlib");
    assert!(
        lean.contains("import PhysicsGenerator.Basic")
            || lean.contains("import PhysicsGenerator.Axioms.SpecialRelativity"),
        "should import axiom modules"
    );
    assert!(
        lean.contains("theorem rest_energy_auto"),
        "should contain theorem name"
    );
    assert!(lean.contains("ℝ"), "should use real numbers");
    assert!(
        lean.contains("Real.sqrt_sq"),
        "should contain sqrt tactic"
    );
    assert!(
        lean.contains("namespace PhysicsGenerator.Exported"),
        "should have namespace"
    );
}

#[test]
fn test_render_lean_file_sorry_fallback() {
    let proof = ExportableProof {
        name: "unknown_proof".into(),
        statement: Expr::Var("x".into()),
        proof: ProofTree::Axiom([0; 8]),
        description: "test proof".into(),
        imports: vec![],
        domain: Domain::ClassicalMechanics,
        theorem_id: "0000000000000000".into(),
        tactic_used: None,
    };

    let config = ExportConfig::default();
    let lean = render_lean_file(&proof, &config);

    assert!(
        lean.contains("assumption"),
        "axiom proof tree should use assumption tactic"
    );
}

#[test]
fn test_render_lean_file_has_header() {
    let proof = ExportableProof {
        name: "test_thm".into(),
        statement: Expr::Lit(0, 1),
        proof: ProofTree::TacticProof {
            tactic: "trivial".into(),
            proof_term: vec![],
        },
        description: "test description".into(),
        imports: vec![],
        domain: Domain::ClassicalMechanics,
        theorem_id: "1234567890abcdef".into(),
        tactic_used: Some("trivial".into()),
    };

    let config = ExportConfig::default();
    let lean = render_lean_file(&proof, &config);

    assert!(
        lean.contains("test_thm"),
        "should contain theorem name in header"
    );
    assert!(
        lean.contains("test description"),
        "should contain description"
    );
    assert!(
        lean.contains("Auto-generated by Nasrudin"),
        "should note auto-generation"
    );
}
