import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.Mechanics

/-!
# Auto-generated by Nasrudin GA engine

Domain: ClassicalMechanics
Theorem: Auto_t132fb872201c63af

Verify: `lake build PhysicsGenerator.Derived.Auto_t132fb872201c63af`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.Mechanics

/-- Auto-generated theorem -/
theorem Auto_t132fb872201c63af :
    (3 : ℝ) = (((3 : ℝ) / ((2 : ℝ) ^ (1 : ℝ))) ^ (1 : ℝ)) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
