import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.Mechanics

/-!
# Auto-generated by Nasrudin GA engine

Domain: ClassicalMechanics
Theorem: Auto_tebc44b799764e3cf

Verify: `lake build PhysicsGenerator.Derived.Auto_tebc44b799764e3cf`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.Mechanics

/-- Auto-generated theorem -/
theorem Auto_tebc44b799764e3cf :
    (3 : ℝ) = ((2 : ℝ) ^ (3 : ℝ)) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
