import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.Thermodynamics

/-!
# Auto-generated by Nasrudin GA engine

Domain: Thermodynamics
Theorem: Auto_t3bb437e1b3d20bdf

Verify: `lake build PhysicsGenerator.Derived.Auto_t3bb437e1b3d20bdf`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.Thermodynamics

/-- Auto-generated theorem -/
theorem Auto_t3bb437e1b3d20bdf :
    (2 : ℝ) = (3 : ℝ) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
