import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.Thermodynamics

/-!
# Auto-generated by Nasrudin GA engine

Domain: Thermodynamics
Theorem: Auto_t68feb8ca03f261e5

Verify: `lake build PhysicsGenerator.Derived.Auto_t68feb8ca03f261e5`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.Thermodynamics

/-- Auto-generated theorem -/
theorem Auto_t68feb8ca03f261e5 :
    (2 : ℝ) = (2 : ℝ) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
