import PhysicsGenerator.Basic

/-!
# Auto-generated by Nasrudin GA engine

Domain: GeneralRelativity
Theorem: Auto_t90ce4be3cf74ff0f

Verify: `lake build PhysicsGenerator.Derived.Auto_t90ce4be3cf74ff0f`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-- Auto-generated theorem -/
theorem Auto_t90ce4be3cf74ff0f :
    ((-(-1 : ℝ)) ^ (3 : ℝ)) = (-(-1 : ℝ)) = (-1 : ℝ) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
