import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.Thermodynamics

/-!
# Auto-generated by Nasrudin GA engine

Domain: Thermodynamics
Theorem: Auto_t726dd2ae9e0ea5ba

Verify: `lake build PhysicsGenerator.Derived.Auto_t726dd2ae9e0ea5ba`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.Thermodynamics

/-- Auto-generated theorem -/
theorem Auto_t726dd2ae9e0ea5ba :
    N_A = N_A := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
