import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by Nasrudin GA engine

Domain: SpecialRelativity
Theorem: Auto_t5f773c891ccf636d

Verify: `lake build PhysicsGenerator.Derived.Auto_t5f773c891ccf636d`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-- Auto-generated theorem -/
theorem Auto_t5f773c891ccf636d :
    (2 : ℝ) = (1 : ℝ) = (0 : ℝ) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
