import PhysicsGenerator.Basic

/-!
# Auto-generated by Nasrudin GA engine

Domain: GeneralRelativity
Theorem: Auto_tf67884840070dee6

Verify: `lake build PhysicsGenerator.Derived.Auto_tf67884840070dee6`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-- Auto-generated theorem -/
theorem Auto_tf67884840070dee6 :
    ((2 : ℝ) ^ (3 : ℝ)) = (-(-1 : ℝ)) = (-1 : ℝ) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
