import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by Nasrudin GA engine

Domain: SpecialRelativity
Theorem: Auto_td680a4d216bbaeec

Verify: `lake build PhysicsGenerator.Derived.Auto_td680a4d216bbaeec`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-- Auto-generated theorem -/
theorem Auto_td680a4d216bbaeec :
    (-(2 : ℝ)) = Real.pi := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
