import PhysicsGenerator.Basic

/-!
# Auto-generated by Nasrudin GA engine

Domain: GeneralRelativity
Theorem: Auto_td827e1b0ec58c843

Verify: `lake build PhysicsGenerator.Derived.Auto_td827e1b0ec58c843`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-- Auto-generated theorem -/
theorem Auto_td827e1b0ec58c843 :
    (-G) = G := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
