import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by Nasrudin GA engine

Domain: SpecialRelativity
Theorem: Auto_t0776e089c3d962dc

Verify: `lake build PhysicsGenerator.Derived.Auto_t0776e089c3d962dc`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-- Auto-generated theorem -/
theorem Auto_t0776e089c3d962dc (m : ℝ) :
    ((((k_B ^ (2 : ℝ)) / ((2 : ℝ) * m)) ^ (2 : ℝ)) / (Real.exp (3 : ℝ))) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
