import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.Electromagnetism

/-!
# Auto-generated by Nasrudin GA engine

Domain: Electromagnetism
Theorem: Auto_t0d2669db994d3a2f

Verify: `lake build PhysicsGenerator.Derived.Auto_t0d2669db994d3a2f`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.Electromagnetism

/-- Auto-generated theorem -/
theorem Auto_t0d2669db994d3a2f :
    (c ^ (2 : ℝ)) = (c ^ (2 : ℝ)) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
