import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.Mechanics

/-!
# Auto-generated by Nasrudin GA engine

Domain: ClassicalMechanics
Theorem: Auto_t3c4c3f28d6c81be0

Verify: `lake build PhysicsGenerator.Derived.Auto_t3c4c3f28d6c81be0`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.Mechanics

/-- Auto-generated theorem -/
theorem Auto_t3c4c3f28d6c81be0 :
    (3 : ℝ) = ((2 : ℝ) ^ (1 : ℝ)) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
