import Mathlib
import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-27 16:44:10 UTC
# Theorem: rest_energy
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-! ## Derivation Steps
  Step 1: Load axiom: mass_shell_condition [introduce_axiom]
  Step 2: Rearrange: E² = p²c² + (mc²)² [rearrange_equation]
  Step 3: Substitute p = n:0 (rest frame) [substitute_value]
  Step 4: Simplify algebraically [algebraic_simplify]
  Step 5: Establish E² = (mc²)² from simplification [canonicalize]
  Step 6: Take positive square root (E ≥ 0, mc² ≥ 0) [take_positive_root]
-/

/-! ## Assumptions
  - rest frame
-/

/-- Auto-derived theorem (chain length 6). -/
theorem rest_energy
    (E m p : ℝ)
    (hE : 0 ≤ E)
    (hm : 0 ≤ m)
    (h_mass_shell_condition : ((E ^ 2) - ((p ^ 2) * (c ^ 2))) = ((m * (c ^ 2)) ^ 2))
    (h_asm0_rest_frame : p = 0)
    : E = (m * (c ^ 2)) := by
  have h_axiom := h_mass_shell_condition
  rw [h_asm0_rest_frame] at h_axiom
  ring_nf at h_axiom
  have h_em : (E ^ 2) = ((m * (c ^ 2)) ^ 2) := by linarith [h_axiom]
  have hmc : 0 ≤ (m * (c ^ 2)) := by positivity
  have h_sqrt := congr_arg Real.sqrt h_em
  rwa [Real.sqrt_sq hE, Real.sqrt_sq hmc] at h_sqrt

end PhysicsGenerator.Derived
