import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by Nasrudin GA engine

Domain: SpecialRelativity
Theorem: Auto_t403a889a212bc06f

Verify: `lake build PhysicsGenerator.Derived.Auto_t403a889a212bc06f`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-- Auto-generated theorem -/
theorem Auto_t403a889a212bc06f :
    ((-1 : ℝ) ^ (3 : ℝ)) = (-1 : ℝ) = (-1 : ℝ) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
