import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by Nasrudin GA engine

Domain: SpecialRelativity
Theorem: Auto_tacdd300cb061b37c

Verify: `lake build PhysicsGenerator.Derived.Auto_tacdd300cb061b37c`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-- Auto-generated theorem -/
theorem Auto_tacdd300cb061b37c :
    (-(-(-(2 : ℝ)))) = Real.pi := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
