import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by Nasrudin GA engine

Domain: SpecialRelativity
Theorem: Auto_tac6b6f81f03b7c01

Verify: `lake build PhysicsGenerator.Derived.Auto_tac6b6f81f03b7c01`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-- Auto-generated theorem -/
theorem Auto_tac6b6f81f03b7c01 :
    Real.pi = (-1 : ℝ) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
