import Mathlib
import PhysicsGenerator.Basic
import PhysicsGenerator.Axioms.SpecialRelativity

/-!
# Auto-generated by nasrudin-derive
# 2026-01-30 11:52:07 UTC
# Theorem: rest_energy
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-! ## Derivation Steps
  Step 1: Load axiom: mass_shell_condition [introduce_axiom]
  Step 2: Rearrange: E² = p²c² + (mc²)² [rearrange_equation]
  Step 3: Substitute p = n:0 (rest frame) [substitute_value]
  Step 4: Simplify algebraically [algebraic_simplify]
  Step 5: Establish E² = (mc²)² from simplification [canonicalize]
  Step 6: Take positive square root (E ≥ 0, mc² ≥ 0) [take_positive_root]
-/

/-! ## Assumptions
  - rest frame
-/

/-- Einstein's mass-energy equivalence: E = mc²
    Auto-derived from mass-shell condition at rest. -/
theorem rest_energy (E m : ℝ)
    (hE : 0 ≤ E) (hm : 0 ≤ m)
    (h_em : E ^ 2 = (m * c ^ 2) ^ 2) :
    E = m * c ^ 2 := by
  have hmc : 0 ≤ m * c ^ 2 := by positivity
  have h_sqrt := congr_arg Real.sqrt h_em
  rwa [Real.sqrt_sq hE, Real.sqrt_sq hmc] at h_sqrt

end PhysicsGenerator.Derived
