import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.Thermodynamics

/-!
# Auto-generated by Nasrudin GA engine

Domain: Thermodynamics
Theorem: Auto_t3ec056ad01d9404a

Verify: `lake build PhysicsGenerator.Derived.Auto_t3ec056ad01d9404a`
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.Thermodynamics

/-- Auto-generated theorem -/
theorem Auto_t3ec056ad01d9404a :
    (Real.sqrt (3 : ℝ)) = (2 : ℝ) := by
  first
  | (omega; done)
  | (norm_num; done)
  | (ring; done)
  | (simp; done)
  | (linarith; done)
  | (field_simp; done)
  | (polyrith; done)
  | (grind; done)

end PhysicsGenerator.Derived
