import Mathlib
import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-28 23:23:49 UTC
# Theorem: beam_0
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-! ## Derivation Steps
  Step 1: Load axiom: invariant_mass_postulate [introduce_axiom]
  Step 2: rearrange toward sr_rest_energy rung 2 [rearrange_equation]
-/

/-- Auto-derived theorem (chain length 2). -/
theorem beam_0
    (E Msq m : ℝ)
    (hE : 0 ≤ E)
    (hm : 0 ≤ m)
    (h_invariant_mass_postulate : Msq = ((m ^ 2) * (c ^ 2)))
    : E = (m * (c ^ 2)) := by
  first
    | (nlinarith [hE, hm, h_invariant_mass_postulate])
    | (linarith [hE, hm, h_invariant_mass_postulate])
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
