import Mathlib
import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-28 23:33:43 UTC
# Theorem: beam_0
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-! ## Derivation Steps
  Step 1: Load axiom: four_momentum_time_component [introduce_axiom]
  Step 2: Load axiom: invariant_mass_postulate [introduce_axiom]
  Step 3: Load axiom: kinetic_energy_def [introduce_axiom]
  Step 4: rearrange toward sr_rest_energy rung 2 [rearrange_equation]
-/

/-- Auto-derived theorem (chain length 4). -/
theorem beam_0
    (E KE Msq m p0 v : ℝ)
    (hE : 0 ≤ E)
    (hm : 0 ≤ m)
    (h_four_momentum_time_component : (c * p0) = E)
    (h_invariant_mass_postulate : Msq = ((m ^ 2) * (c ^ 2)))
    (h_kinetic_energy_def : KE = ((1 / 2) * (m * (v ^ 2))))
    : E = (m * (c ^ 2)) := by
  first
    | (nlinarith [hE, hm, h_four_momentum_time_component, h_invariant_mass_postulate, h_kinetic_energy_def])
    | (linarith [hE, hm, h_four_momentum_time_component, h_invariant_mass_postulate, h_kinetic_energy_def])
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
