import Mathlib
import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-27 17:28:02 UTC
# Theorem: rest_energy_chain_test
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-! ## Derivation Steps
  Step 1: Load axiom: four_momentum_time_component [introduce_axiom]
  Step 2: Load axiom: minkowski_invariant_def [introduce_axiom]
  Step 3: Load axiom: invariant_mass_postulate [introduce_axiom]
  Step 4: Load axiom: rest_frame_psq_zero [introduce_axiom]
  Step 5: E² = (m·c²)² from upstream axioms [rearrange_equation]
  Step 6: Take positive square root (E ≥ 0, mc² ≥ 0) [take_positive_root]
-/

/-- Auto-derived theorem (chain length 6). -/
theorem rest_energy_chain_test
    (E Msq m p0 psq : ℝ)
    (hE : 0 ≤ E)
    (hm : 0 ≤ m)
    (h_four_momentum_time_component : (c * p0) = E)
    (h_minkowski_invariant_def : Msq = ((p0 ^ 2) - psq))
    (h_invariant_mass_postulate : Msq = ((m ^ 2) * (c ^ 2)))
    (h_rest_frame_psq_zero : psq = 0)
    : E = (m * (c ^ 2)) := by
  have h_em : (E ^ 2) = ((m * (c ^ 2)) ^ 2) := by
    first
      | (nlinarith [hE, hm, h_four_momentum_time_component, h_minkowski_invariant_def, h_invariant_mass_postulate, h_rest_frame_psq_zero, sq_nonneg (E), sq_nonneg ((m * (c ^ 2)))])
      | (polyrith)
      | (linear_combination 0)
  have hmc : 0 ≤ (m * (c ^ 2)) := by positivity
  have h_sqrt := congr_arg Real.sqrt h_em
  rwa [Real.sqrt_sq hE, Real.sqrt_sq hmc] at h_sqrt

end PhysicsGenerator.Derived
