import PhysicsGenerator.LeafImports
import PhysicsGenerator.Basic

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# Theorem: derive_qsl
-/

set_option maxHeartbeats 50000

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-! ## Derivation Steps
  Step 1: Load axiom: qm_schrodinger_evolution [introduce_axiom]
  Step 2: Load axiom: qm_eigenvalue_equation [introduce_axiom]
  Step 3: Load axiom: qm_hbar_positive [introduce_axiom]
  Step 4: Simplify algebraically [algebraic_simplify]
-/

/-- Auto-derived theorem (chain length 4). -/
theorem derive_qsl
    (A_op : ℝ → ℝ)
    (H_op : ℝ → ℝ)
    (a d_psi_d_t i_unit psi : ℝ)
    (h_qm_schrodinger_evolution : ((i_unit * hbar) * d_psi_d_t) = (H_op psi))
    (h_qm_eigenvalue_equation : (A_op psi) = (a * psi))
    (h_qm_hbar_positive : hbar > 0)
    : hbar > 0 := by
  first
    | exact h_qm_schrodinger_evolution
    | exact h_qm_eigenvalue_equation
    | exact h_qm_hbar_positive
    | (nlinarith [h_qm_schrodinger_evolution, h_qm_eigenvalue_equation, h_qm_hbar_positive])
    | (linarith [h_qm_schrodinger_evolution, h_qm_eigenvalue_equation, h_qm_hbar_positive])
    | (ring_nf at * <;> nlinarith [h_qm_schrodinger_evolution, h_qm_eigenvalue_equation, h_qm_hbar_positive])
    | (linear_combination 0)
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
