import PhysicsGenerator.LeafImports
import PhysicsGenerator.Basic

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# Theorem: derive_dispersion
-/

set_option maxHeartbeats 50000

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-! ## Derivation Steps
  Step 1: Load axiom: qm_schrodinger_evolution [introduce_axiom]
  Step 2: Load axiom: qm_free_hamiltonian [introduce_axiom]
  Step 3: Load axiom: qm_eigenvalue_equation [introduce_axiom]
  Step 4: Simplify algebraically [algebraic_simplify]
-/

/-- Auto-derived theorem (chain length 4). -/
theorem derive_dispersion
    (A_op : ℝ → ℝ)
    (H_op : ℝ → ℝ)
    (H_free a d_psi_d_t i_unit m p_op psi : ℝ)
    (hm : 0 ≤ m)
    (h_qm_schrodinger_evolution : ((i_unit * hbar) * d_psi_d_t) = (H_op psi))
    (h_qm_free_hamiltonian : H_free = ((p_op ^ 2) / (2 * m)))
    (h_qm_eigenvalue_equation : (A_op psi) = (a * psi))
    : (A_op psi) = (a * psi) := by
  first
    | exact hm
    | exact h_qm_schrodinger_evolution
    | exact h_qm_free_hamiltonian
    | exact h_qm_eigenvalue_equation
    | (nlinarith [hm, h_qm_schrodinger_evolution, h_qm_free_hamiltonian, h_qm_eigenvalue_equation])
    | (linarith [hm, h_qm_schrodinger_evolution, h_qm_free_hamiltonian, h_qm_eigenvalue_equation])
    | (ring_nf at * <;> nlinarith [hm, h_qm_schrodinger_evolution, h_qm_free_hamiltonian, h_qm_eigenvalue_equation])
    | (linear_combination 0)
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
