import Mathlib
import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-27 23:32:25 UTC
# Theorem: discover_gen14
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-! ## Derivation Steps
  Step 1: Load axiom: invariant_mass_postulate [introduce_axiom]
  Step 2: Load axiom: four_momentum_time_component [introduce_axiom]
  Step 3: Load axiom: mass_nonneg [introduce_axiom]
  Step 4: Load axiom: minkowski_invariant_def [introduce_axiom]
  Step 5: Load axiom: rest_frame_psq_zero [introduce_axiom]
  Step 6: Suffix: X²=Y² for take-root [rearrange_equation]
  Step 7: Take positive square root (E ≥ 0, mc² ≥ 0) [take_positive_root]
  Step 8: Simplify algebraically [algebraic_simplify]
-/

/-- Auto-derived theorem (chain length 8). -/
theorem discover_gen14
    (E Msq m p0 psq : ℝ)
    (hE : 0 ≤ E)
    (hm : 0 ≤ m)
    (h_invariant_mass_postulate : Msq = ((m ^ 2) * (c ^ 2)))
    (h_four_momentum_time_component : (c * p0) = E)
    (h_mass_nonneg : m ≥ 0)
    (h_minkowski_invariant_def : Msq = ((p0 ^ 2) - psq))
    (h_rest_frame_psq_zero : psq = 0)
    : Msq = (p0 ^ 2) := by
  first
    | (nlinarith [hE, hm, h_invariant_mass_postulate, h_four_momentum_time_component, h_mass_nonneg, h_minkowski_invariant_def, h_rest_frame_psq_zero])
    | (linarith [hE, hm, h_invariant_mass_postulate, h_four_momentum_time_component, h_mass_nonneg, h_minkowski_invariant_def, h_rest_frame_psq_zero])
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
