import PhysicsGenerator.LeafImports
import PhysicsGenerator.Basic

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# Theorem: discover_gen0
-/

set_option maxHeartbeats 50000

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-! ## Derivation Steps
  Step 1: Load axiom: hbar_positive [introduce_axiom]
  Step 2: Load axiom: photon_energy_def [introduce_axiom]
  Step 3: Simplify algebraically [algebraic_simplify]
-/

/-- Auto-derived theorem (chain length 3). -/
theorem discover_gen0
    (Eph hbar omega : ℝ)
    (h_hbar_positive : hbar > 0)
    (h_photon_energy_def : Eph = (hbar * omega))
    : Eph = (hbar * omega) := by
  first
    | exact h_hbar_positive
    | exact h_photon_energy_def
    | (nlinarith [h_hbar_positive, h_photon_energy_def])
    | (linarith [h_hbar_positive, h_photon_energy_def])
    | (ring_nf at * <;> nlinarith [h_hbar_positive, h_photon_energy_def])
    | (linear_combination 0)
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
