import Mathlib
import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-27 23:13:13 UTC
# Theorem: discover_gen8
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-! ## Derivation Steps
  Step 1: Load axiom: rest_frame_psq_zero [introduce_axiom]
  Step 2: Load axiom: minkowski_invariant_def [introduce_axiom]
  Step 3: Load axiom: mass_nonneg [introduce_axiom]
  Step 4: Load axiom: mass_nonneg [introduce_axiom]
  Step 5: Load axiom: invariant_mass_postulate [introduce_axiom]
  Step 6: Load axiom: rest_frame_psq_zero [introduce_axiom]
  Step 7: Load axiom: mass_nonneg [introduce_axiom]
  Step 8: Load axiom: minkowski_invariant_def [introduce_axiom]
-/

/-- Auto-derived theorem (chain length 8). -/
theorem discover_gen8
    (Msq m p0 psq : ℝ)
    (hm : 0 ≤ m)
    (h_rest_frame_psq_zero : psq = 0)
    (h_minkowski_invariant_def : Msq = ((p0 ^ 2) - psq))
    (h_mass_nonneg : m ≥ 0)
    (h_mass_nonneg : m ≥ 0)
    (h_invariant_mass_postulate : Msq = ((m ^ 2) * (c ^ 2)))
    (h_rest_frame_psq_zero : psq = 0)
    (h_mass_nonneg : m ≥ 0)
    (h_minkowski_invariant_def : Msq = ((p0 ^ 2) - psq))
    : Msq = ((p0 ^ 2) - psq) := by
  first
    | (nlinarith [hm, h_rest_frame_psq_zero, h_minkowski_invariant_def, h_mass_nonneg, h_mass_nonneg, h_invariant_mass_postulate, h_rest_frame_psq_zero, h_mass_nonneg, h_minkowski_invariant_def])
    | (linarith [hm, h_rest_frame_psq_zero, h_minkowski_invariant_def, h_mass_nonneg, h_mass_nonneg, h_invariant_mass_postulate, h_rest_frame_psq_zero, h_mass_nonneg, h_minkowski_invariant_def])
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
