import Mathlib
import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-28 23:41:53 UTC
# Theorem: discover_gen2
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-! ## Derivation Steps
  Step 1: Load axiom: lorentz_contrcotomatrix_ρ_symm [introduce_axiom]
  Step 2: Synthesised target [rearrange_equation]
  Step 3: Load axiom: lorentz_velocity_zero_le_minkowskiproduct [introduce_axiom]
  Step 4: Load axiom: lorentzgroup_orthchromapreal_minus_one_or_one [introduce_axiom]
  Step 5: Load axiom: lorentz_covector_isnormedspace [introduce_axiom]
  Step 6: Load axiom: lorentz_contrcontrtomatrix_ρ_symm [introduce_axiom]
  Step 7: Load axiom: spacetime_schwartzaction_apply [introduce_axiom]
  Step 8: Load axiom: invariant_mass_postulate [introduce_axiom]
-/

/-- Auto-derived theorem (chain length 8). -/
theorem discover_gen2
    (Msq lorentz_contrcontrtomatrix_ρ_symm lorentz_contrcotomatrix_ρ_symm lorentz_covector_isnormedspace lorentz_velocity_zero_le_minkowskiproduct lorentzgroup_orthchromapreal_minus_one_or_one m spacetime_schwartzaction_apply : ℝ)
    (hm : 0 ≤ m)
    (h_lorentz_contrcotomatrix_ρ_symm : lorentz_contrcotomatrix_ρ_symm)
    (h_lorentz_velocity_zero_le_minkowskiproduct : lorentz_velocity_zero_le_minkowskiproduct)
    (h_lorentzgroup_orthchromapreal_minus_one_or_one : lorentzgroup_orthchromapreal_minus_one_or_one)
    (h_lorentz_covector_isnormedspace : lorentz_covector_isnormedspace)
    (h_lorentz_contrcontrtomatrix_ρ_symm : lorentz_contrcontrtomatrix_ρ_symm)
    (h_spacetime_schwartzaction_apply : spacetime_schwartzaction_apply)
    (h_invariant_mass_postulate : Msq = ((m ^ 2) * (c ^ 2)))
    : Msq = ((m ^ 2) * (c ^ 2)) := by
  first
    | (nlinarith [hm, h_lorentz_contrcotomatrix_ρ_symm, h_lorentz_velocity_zero_le_minkowskiproduct, h_lorentzgroup_orthchromapreal_minus_one_or_one, h_lorentz_covector_isnormedspace, h_lorentz_contrcontrtomatrix_ρ_symm, h_spacetime_schwartzaction_apply, h_invariant_mass_postulate])
    | (linarith [hm, h_lorentz_contrcotomatrix_ρ_symm, h_lorentz_velocity_zero_le_minkowskiproduct, h_lorentzgroup_orthchromapreal_minus_one_or_one, h_lorentz_covector_isnormedspace, h_lorentz_contrcontrtomatrix_ρ_symm, h_spacetime_schwartzaction_apply, h_invariant_mass_postulate])
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
