import PhysicsGenerator.LeafImports
import PhysicsGenerator.Basic

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# Theorem: discover_gen3
-/

set_option maxHeartbeats 50000

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-! ## Derivation Steps
  Step 1: Load axiom: minkowski_invariant_def [introduce_axiom]
  Step 2: Load axiom: energy_nonneg [introduce_axiom]
  Step 3: Load axiom: work_def [introduce_axiom]
  Step 4: Load axiom: power_def [introduce_axiom]
  Step 5: Load axiom: newton_second [introduce_axiom]
  Step 6: Load axiom: power_def [introduce_axiom]
  Step 7: Load axiom: energy_nonneg [introduce_axiom]
  Step 8: Load axiom: mass_nonneg [introduce_axiom]
  Step 9: E² = (m·c²)² from upstream axioms [rearrange_equation]
-/

/-- Auto-derived theorem (chain length 9). -/
theorem discover_gen3
    (E F Msq P W a d m p0 psq : ℝ)
    (hE : 0 ≤ E)
    (hm : 0 ≤ m)
    (h_minkowski_invariant_def : Msq = ((p0 ^ 2) - psq))
    (h_energy_nonneg : E ≥ 0)
    (h_work_def : W = (F * d))
    (h_power_def : P = sorry /- Deriv(Var("W"), "t") -/)
    (h_newton_second : F = (m * a))
    (h_power_def : P = sorry /- Deriv(Var("W"), "t") -/)
    (h_energy_nonneg : E ≥ 0)
    (h_mass_nonneg : m ≥ 0)
    : (E ^ 2) = ((m * (c ^ 2)) ^ 2) := by
  first
    | (nlinarith [hE, hm, h_minkowski_invariant_def, h_energy_nonneg, h_work_def, h_power_def, h_newton_second, h_power_def, h_energy_nonneg, h_mass_nonneg])
    | (linarith [hE, hm, h_minkowski_invariant_def, h_energy_nonneg, h_work_def, h_power_def, h_newton_second, h_power_def, h_energy_nonneg, h_mass_nonneg])
    | (ring_nf at * <;> nlinarith [hE, hm, h_minkowski_invariant_def, h_energy_nonneg, h_work_def, h_power_def, h_newton_second, h_power_def, h_energy_nonneg, h_mass_nonneg])
    | (linear_combination 0)
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
