import PhysicsGenerator.LeafImports
import PhysicsGenerator.Basic

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# Theorem: discover_gen4
-/

set_option maxHeartbeats 50000

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-! ## Derivation Steps
  Step 1: Load axiom: minkowski_invariant_def [introduce_axiom]
  Step 2: Load axiom: acceleration_def [introduce_axiom]
  Step 3: Load axiom: newton_second [introduce_axiom]
  Step 4: Load axiom: velocity_def [introduce_axiom]
  Step 5: Load axiom: four_momentum_time_component [introduce_axiom]
  Step 6: Load axiom: minkowski_invariant_def [introduce_axiom]
  Step 7: Load axiom: invariant_mass_postulate [introduce_axiom]
  Step 8: Load axiom: rest_frame_psq_zero [introduce_axiom]
  Step 9: Load axiom: energy_nonneg [introduce_axiom]
  Step 10: Load axiom: mass_nonneg [introduce_axiom]
  Step 11: E² = (m·c²)² from upstream axioms [rearrange_equation]
-/

/-- Auto-derived theorem (chain length 11). -/
theorem discover_gen4
    (E F Msq a m p0 psq v : ℝ)
    (hE : 0 ≤ E)
    (hm : 0 ≤ m)
    (h_minkowski_invariant_def : Msq = ((p0 ^ 2) - psq))
    (h_acceleration_def : a = sorry /- Deriv(Var("v"), "t") -/)
    (h_newton_second : F = (m * a))
    (h_velocity_def : v = sorry /- Deriv(Var("x"), "t") -/)
    (h_four_momentum_time_component : (c * p0) = E)
    (h_minkowski_invariant_def : Msq = ((p0 ^ 2) - psq))
    (h_invariant_mass_postulate : Msq = ((m ^ 2) * (c ^ 2)))
    (h_rest_frame_psq_zero : psq = 0)
    (h_energy_nonneg : E ≥ 0)
    (h_mass_nonneg : m ≥ 0)
    : (E ^ 2) = ((m * (c ^ 2)) ^ 2) := by
  first
    | (nlinarith [hE, hm, h_minkowski_invariant_def, h_acceleration_def, h_newton_second, h_velocity_def, h_four_momentum_time_component, h_minkowski_invariant_def, h_invariant_mass_postulate, h_rest_frame_psq_zero, h_energy_nonneg, h_mass_nonneg])
    | (linarith [hE, hm, h_minkowski_invariant_def, h_acceleration_def, h_newton_second, h_velocity_def, h_four_momentum_time_component, h_minkowski_invariant_def, h_invariant_mass_postulate, h_rest_frame_psq_zero, h_energy_nonneg, h_mass_nonneg])
    | (ring_nf at * <;> nlinarith [hE, hm, h_minkowski_invariant_def, h_acceleration_def, h_newton_second, h_velocity_def, h_four_momentum_time_component, h_minkowski_invariant_def, h_invariant_mass_postulate, h_rest_frame_psq_zero, h_energy_nonneg, h_mass_nonneg])
    | (linear_combination 0)
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
