import Mathlib
import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-27 22:48:52 UTC
# Theorem: discover_gen1
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-! ## Derivation Steps
  Step 1: Synthesised target [rearrange_equation]
  Step 2: Load axiom: invariant_mass_postulate [introduce_axiom]
  Step 3: Load axiom: rest_frame_psq_zero [introduce_axiom]
  Step 4: Load axiom: energy_nonneg [introduce_axiom]
  Step 5: Load axiom: mass_nonneg [introduce_axiom]
  Step 6: Load axiom: minkowski_invariant_def [introduce_axiom]
  Step 7: Load axiom: c_positive [introduce_axiom]
  Step 8: Load axiom: four_momentum_time_component [introduce_axiom]
-/

/-- Auto-derived theorem (chain length 8). -/
theorem discover_gen1
    (E Msq m p0 psq : ℝ)
    (hE : 0 ≤ E)
    (hm : 0 ≤ m)
    (h_invariant_mass_postulate : Msq = ((m ^ 2) * (c ^ 2)))
    (h_rest_frame_psq_zero : psq = 0)
    (h_energy_nonneg : E ≥ 0)
    (h_mass_nonneg : m ≥ 0)
    (h_minkowski_invariant_def : Msq = ((p0 ^ 2) - psq))
    (h_c_positive : c > 0)
    (h_four_momentum_time_component : (c * p0) = E)
    : (c * p0) = E := by
  first
    | (nlinarith [hE, hm, h_invariant_mass_postulate, h_rest_frame_psq_zero, h_energy_nonneg, h_mass_nonneg, h_minkowski_invariant_def, h_c_positive, h_four_momentum_time_component])
    | (linarith [hE, hm, h_invariant_mass_postulate, h_rest_frame_psq_zero, h_energy_nonneg, h_mass_nonneg, h_minkowski_invariant_def, h_c_positive, h_four_momentum_time_component])
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
