import PhysicsGenerator.LeafImports
import PhysicsGenerator.Basic

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# Theorem: discover_gen0
-/

set_option maxHeartbeats 50000

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-! ## Derivation Steps
  Step 1: Load axiom: four_momentum_time_component [introduce_axiom]
  Step 2: Load axiom: minkowski_invariant_def [introduce_axiom]
  Step 3: Load axiom: invariant_mass_postulate [introduce_axiom]
  Step 4: Load axiom: rest_frame_psq_zero [introduce_axiom]
  Step 5: Load axiom: energy_nonneg [introduce_axiom]
  Step 6: Load axiom: mass_nonneg [introduce_axiom]
  Step 7: E² = (m·c²)² from upstream axioms [rearrange_equation]
  Step 8: Take positive square root (LHS ≥ 0, RHS ≥ 0 from ctx) [take_positive_root]
-/

/-- Auto-derived theorem (chain length 8). -/
theorem discover_gen0
    (E Msq m p0 psq : ℝ)
    (hE : 0 ≤ E)
    (hm : 0 ≤ m)
    (h_four_momentum_time_component : (c * p0) = E)
    (h_minkowski_invariant_def : Msq = ((p0 ^ 2) - psq))
    (h_invariant_mass_postulate : Msq = ((m ^ 2) * (c ^ 2)))
    (h_rest_frame_psq_zero : psq = 0)
    (h_energy_nonneg : E ≥ 0)
    (h_mass_nonneg : m ≥ 0)
    : E = (m * (c ^ 2)) := by
  have h_em : (E ^ 2) = ((m * (c ^ 2)) ^ 2) := by
    first
      | (nlinarith [hE, hm, h_four_momentum_time_component, h_minkowski_invariant_def, h_invariant_mass_postulate, h_rest_frame_psq_zero, h_energy_nonneg, h_mass_nonneg, sq_nonneg (E), sq_nonneg ((m * (c ^ 2)))])
      | (linarith [hE, hm, h_four_momentum_time_component, h_minkowski_invariant_def, h_invariant_mass_postulate, h_rest_frame_psq_zero, h_energy_nonneg, h_mass_nonneg, sq_nonneg (E), sq_nonneg ((m * (c ^ 2)))])
      | (ring_nf at * <;> nlinarith [hE, hm, h_four_momentum_time_component, h_minkowski_invariant_def, h_invariant_mass_postulate, h_rest_frame_psq_zero, h_energy_nonneg, h_mass_nonneg, sq_nonneg (E), sq_nonneg ((m * (c ^ 2)))])
      | (linear_combination 0)
  have hmc : 0 ≤ (m * (c ^ 2)) := by positivity
  have h_sqrt := congr_arg Real.sqrt h_em
  rwa [Real.sqrt_sq hE, Real.sqrt_sq hmc] at h_sqrt

end PhysicsGenerator.Derived
