import Mathlib
import PhysicsGenerator.Basic
import PhysicsGenerator.Generated.SpecialRelativity

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-28 15:06:06 UTC
# Theorem: discover_gen61
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator
open PhysicsGenerator.SpecialRelativity

/-! ## Derivation Steps
  Step 1: Synthesised target [rearrange_equation]
-/

/-- Auto-derived theorem (chain length 1). -/
theorem discover_gen61
    (p0 : ℝ)
    : ((0 * p0) ^ 2) = ((c * p0) ^ 2) := by
  first
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
