import PhysicsGenerator.LeafImports
import PhysicsGenerator.Basic

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-29 23:38:07 UTC
# Theorem: submit_gen2_0
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-! ## Derivation Steps
  Step 1: Load axiom: fermion_leftbasis_eq_1 [introduce_axiom]
-/

/-- Auto-derived theorem (chain length 1). -/
theorem submit_gen2_0
    (Complex Equiv.linearEquiv Fermion.LeftHandedModule.toFin2ℂFun Fermion.leftBasis Module.Basis.ofEquivFun : ℝ)
    (h_fermion_leftbasis_eq_1 : Fermion.leftBasis = (Module.Basis.ofEquivFun ((Equiv.linearEquiv Complex) Fermion.LeftHandedModule.toFin2ℂFun)))
    : Fermion.leftBasis = (Module.Basis.ofEquivFun ((Equiv.linearEquiv Complex) Fermion.LeftHandedModule.toFin2ℂFun)) := by
  first
    | (nlinarith [h_fermion_leftbasis_eq_1])
    | (linarith [h_fermion_leftbasis_eq_1])
    | ring
    | norm_num
    | simp
    | grind

end PhysicsGenerator.Derived
