import PhysicsGenerator.LeafImports
import PhysicsGenerator.Basic

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-29 23:38:31 UTC
# Theorem: submit_gen2_0
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-! ## Derivation Steps
  Step 1: Load axiom: complexlorentztensor_rightaltrightunit_eq_fromconstpair [introduce_axiom]
  Step 2: Load axiom: cliffordalgebra_ι_mul_ι_mul_ι [introduce_axiom]
  Step 3: Load axiom: int_mul_tdiv_assoc' [introduce_axiom]
  Step 4: Load axiom: electromagnetism_electromagneticpotential_electricfield [introduce_axiom]
  Step 5: Load axiom: nat_linear_expr_topoly_go_eq_5 [introduce_axiom]
  Step 6: Load axiom: lorentz_contrcontrcontractfield_same_eq_det_toselfadjoint [introduce_axiom]
  Step 7: Suffix: X²=Y² for take-root [rearrange_equation]
  Step 8: Take positive square root (E ≥ 0, mc² ≥ 0) [take_positive_root]
-/

/-- Auto-derived theorem (chain length 8). -/
theorem submit_gen2_0
    (Fermion.rightAltRightUnit TensorSpecies.Tensor.fromConstPair complexLorentzTensor.rightAltRightUnit p0 : ℝ)
    (h_complexlorentztensor_rightaltrightunit_eq_fromconstpair : complexLorentzTensor.rightAltRightUnit = (TensorSpecies.Tensor.fromConstPair Fermion.rightAltRightUnit))
    (h_cliffordalgebra_ι_mul_ι_mul_ι : (∀ (R : _anon), (∀ (inst.__.Mathlib.LinearAlgebra.CliffordAlgebra.Basic.4103318905._hygCtx._hyg.3 : (CommRing R)), (∀ (M : _anon), (∀ (inst.__.Mathlib.LinearAlgebra.CliffordAlgebra.Basic.4103318905._hygCtx._hyg.7 : (AddCommGroup M)), (∀ (inst.__.Mathlib.LinearAlgebra.CliffordAlgebra.Basic.4103318905._hygCtx._hyg.10 : ((Module R) M)), (∀ (Q : ((QuadraticForm R) M)), (∀ (a : M), (∀ (b : M), ((((DFunLike.coe (CliffordAlgebra.ι Q)) a) * ((DFunLike.coe (CliffordAlgebra.ι Q)) b)) * ((DFunLike.coe (CliffordAlgebra.ι Q)) a)) = ((DFunLike.coe (CliffordAlgebra.ι Q)) (((HSMul.hSMul (((QuadraticMap.polar (DFunLike.coe Q)) a) b)) a) - ((HSMul.hSMul ((DFunLike.coe Q) a)) b))))))))))))
    (h_int_mul_tdiv_assoc_ : (∀ (b : Int), (∀ (a : Int), (∀ (c : Int), (((Dvd.dvd c) a) → ((Int.tdiv (a * b)) c) = (((Int.tdiv a) c) * b))))))
    (h_electromagnetism_electromagneticpotential_electricfield : (∀ (d : Nat), (∀ (c : ((optParam SpeedOfLight) 1)), (∀ (A : (Electromagnetism.ElectromagneticPotential d)), (Electromagnetism.ElectricField d)))))
    (h_nat_linear_expr_topoly_go_eq_5 : (∀ (coeff : Nat), (∀ (a : Nat.Linear.Expr), (∀ (k : Nat), ((Nat.Linear.Expr.toPoly.go coeff) ((Nat.Linear.Expr.mulR a) k)) = (((cond ((BEq.beq k) 0)) id) ((Nat.Linear.Expr.toPoly.go (coeff * k)) a))))))
    (h_lorentz_contrcontrcontractfield_same_eq_det_toselfadjoint : (∀ (x : (Lorentz.ContrMod 3)), (Complex.ofReal ((DFunLike.coe Lorentz.contrContrContractField) (((TensorProduct.tmul Real) x) x))) = (Matrix.det (Subtype.val ((DFunLike.coe Lorentz.ContrMod.toSelfAdjoint) x)))))
    : (c * p0) = complexLorentzTensor.rightAltRightUnit := by
  have h_em : ((c * p0) ^ 2) = (complexLorentzTensor.rightAltRightUnit ^ 2) := by
    first
      | (nlinarith [h_complexlorentztensor_rightaltrightunit_eq_fromconstpair, h_cliffordalgebra_ι_mul_ι_mul_ι, h_int_mul_tdiv_assoc_, h_electromagnetism_electromagneticpotential_electricfield, h_nat_linear_expr_topoly_go_eq_5, h_lorentz_contrcontrcontractfield_same_eq_det_toselfadjoint, sq_nonneg ((c * p0)), sq_nonneg (complexLorentzTensor.rightAltRightUnit)])
      | (polyrith)
      | (linear_combination 0)
  have hmc : 0 ≤ complexLorentzTensor.rightAltRightUnit := by positivity
  have h_sqrt := congr_arg Real.sqrt h_em
  rwa [Real.sqrt_sq (by nlinarith [h_complexlorentztensor_rightaltrightunit_eq_fromconstpair, h_cliffordalgebra_ι_mul_ι_mul_ι, h_int_mul_tdiv_assoc_, h_electromagnetism_electromagneticpotential_electricfield, h_nat_linear_expr_topoly_go_eq_5, h_lorentz_contrcontrcontractfield_same_eq_det_toselfadjoint, sq_nonneg ((c * p0)), sq_nonneg (complexLorentzTensor.rightAltRightUnit)] : 0 ≤ (c * p0)), Real.sqrt_sq hmc] at h_sqrt

end PhysicsGenerator.Derived
