import PhysicsGenerator.LeafImports
import PhysicsGenerator.Basic

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-29 23:38:15 UTC
# Theorem: submit_gen8_2
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-! ## Derivation Steps
  Step 1: Load axiom: electromagnetism_distelectromagneticpotential_isextrema [introduce_axiom]
  Step 2: Load axiom: real_continuousat_rpow_of_pos [introduce_axiom]
  Step 3: Load axiom: nat_clog_pow_left [introduce_axiom]
  Step 4: Load axiom: nat_instisstrictorderedring [introduce_axiom]
  Step 5: Load axiom: int_fmod_eq_zero_of_dvd [introduce_axiom]
  Step 6: Load axiom: real_dist_eq [introduce_axiom]
  Step 7: Load axiom: int_linear_poly_isnegeq [introduce_axiom]
  Step 8: Load axiom: int_linear_poly_isnegeq [introduce_axiom]
  Step 9: Load axiom: fermion_altrightrightunit_symm [introduce_axiom]
  Step 10: Suffix: X²=Y² for take-root [rearrange_equation]
  Step 11: Take positive square root (E ≥ 0, mc² ≥ 0) [take_positive_root]
-/

/-- Auto-derived theorem (chain length 11). -/
theorem submit_gen8_2
    (Action.Hom.hom CategoryTheory.BraidedCategory.braiding CategoryTheory.CategoryStruct.id CategoryTheory.ConcreteCategory.hom CategoryTheory.Iso.hom CategoryTheory.MonoidalCategoryStruct.whiskerLeft DFunLike.coe Fermion.altRightHanded Fermion.altRightRightUnit Fermion.rightAltRightUnit Fermion.rightHanded IsStrictOrderedRing Nat p0 : ℝ)
    (h_electromagnetism_distelectromagneticpotential_isextrema : (∀ (d : Nat), (∀ (𝓕 : Electromagnetism.FreeSpace), (∀ (A : (Electromagnetism.DistElectromagneticPotential d)), (∀ (J : (Electromagnetism.DistLorentzCurrentDensity d)), _anon)))))
    (h_real_continuousat_rpow_of_pos : (∀ (p : ((Prod Real) Real)), (0 < (Prod.snd p) → ((ContinuousAt (fun (p : ((Prod Real) Real)) => ((Prod.fst p) ^ (Prod.snd p)))) p))))
    (h_nat_clog_pow_left : (∀ (b : Nat), (∀ (k : Nat), (∀ (n : Nat), ((Nat.clog (b ^ k)) n) = ((((Nat.clog b) n) + (k - 1)) / k)))))
    (h_nat_instisstrictorderedring : (IsStrictOrderedRing Nat))
    (h_int_fmod_eq_zero_of_dvd : (∀ (a : Int), (∀ (b : Int), (((Dvd.dvd a) b) → ((Int.fmod b) a) = 0))))
    (h_real_dist_eq : (∀ (x : Real), (∀ (y : Real), ((Dist.dist x) y) = |(x - y)|)))
    (h_int_linear_poly_isnegeq : (∀ (p₁ : Int.Linear.Poly), (∀ (p₂ : Int.Linear.Poly), Bool)))
    (h_int_linear_poly_isnegeq : (∀ (p₁ : Int.Linear.Poly), (∀ (p₂ : Int.Linear.Poly), Bool)))
    (h_fermion_altrightrightunit_symm : ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom Fermion.altRightRightUnit))) 1) = ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom ((CategoryTheory.MonoidalCategoryStruct.whiskerLeft Fermion.altRightHanded) (CategoryTheory.CategoryStruct.id Fermion.rightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom (CategoryTheory.Iso.hom ((CategoryTheory.BraidedCategory.braiding Fermion.rightHanded) Fermion.altRightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom Fermion.rightAltRightUnit))) 1))))
    : ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom ((CategoryTheory.MonoidalCategoryStruct.whiskerLeft Fermion.altRightHanded) (CategoryTheory.CategoryStruct.id Fermion.rightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom (CategoryTheory.Iso.hom ((CategoryTheory.BraidedCategory.braiding Fermion.rightHanded) Fermion.altRightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom Fermion.rightAltRightUnit))) 1))) = (c * p0) := by
  have h_em : (((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom ((CategoryTheory.MonoidalCategoryStruct.whiskerLeft Fermion.altRightHanded) (CategoryTheory.CategoryStruct.id Fermion.rightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom (CategoryTheory.Iso.hom ((CategoryTheory.BraidedCategory.braiding Fermion.rightHanded) Fermion.altRightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom Fermion.rightAltRightUnit))) 1))) ^ 2) = ((c * p0) ^ 2) := by
    first
      | (nlinarith [h_electromagnetism_distelectromagneticpotential_isextrema, h_real_continuousat_rpow_of_pos, h_nat_clog_pow_left, h_nat_instisstrictorderedring, h_int_fmod_eq_zero_of_dvd, h_real_dist_eq, h_int_linear_poly_isnegeq, h_int_linear_poly_isnegeq, h_fermion_altrightrightunit_symm, sq_nonneg (((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom ((CategoryTheory.MonoidalCategoryStruct.whiskerLeft Fermion.altRightHanded) (CategoryTheory.CategoryStruct.id Fermion.rightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom (CategoryTheory.Iso.hom ((CategoryTheory.BraidedCategory.braiding Fermion.rightHanded) Fermion.altRightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom Fermion.rightAltRightUnit))) 1)))), sq_nonneg ((c * p0))])
      | (polyrith)
      | (linear_combination 0)
  have hmc : 0 ≤ (c * p0) := by positivity
  have h_sqrt := congr_arg Real.sqrt h_em
  rwa [Real.sqrt_sq (by nlinarith [h_electromagnetism_distelectromagneticpotential_isextrema, h_real_continuousat_rpow_of_pos, h_nat_clog_pow_left, h_nat_instisstrictorderedring, h_int_fmod_eq_zero_of_dvd, h_real_dist_eq, h_int_linear_poly_isnegeq, h_int_linear_poly_isnegeq, h_fermion_altrightrightunit_symm, sq_nonneg (((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom ((CategoryTheory.MonoidalCategoryStruct.whiskerLeft Fermion.altRightHanded) (CategoryTheory.CategoryStruct.id Fermion.rightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom (CategoryTheory.Iso.hom ((CategoryTheory.BraidedCategory.braiding Fermion.rightHanded) Fermion.altRightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom Fermion.rightAltRightUnit))) 1)))), sq_nonneg ((c * p0))] : 0 ≤ ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom ((CategoryTheory.MonoidalCategoryStruct.whiskerLeft Fermion.altRightHanded) (CategoryTheory.CategoryStruct.id Fermion.rightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom (CategoryTheory.Iso.hom ((CategoryTheory.BraidedCategory.braiding Fermion.rightHanded) Fermion.altRightHanded))))) ((DFunLike.coe (CategoryTheory.ConcreteCategory.hom (Action.Hom.hom Fermion.rightAltRightUnit))) 1)))), Real.sqrt_sq hmc] at h_sqrt

end PhysicsGenerator.Derived
