import PhysicsGenerator.LeafImports
import PhysicsGenerator.Basic

/-!
# Auto-generated by nasrudin-derive (chain emitter v2)
# 2026-04-29 23:38:28 UTC
# Theorem: submit_gen0_0
-/

namespace PhysicsGenerator.Derived

open PhysicsGenerator

/-! ## Derivation Steps
  Step 1: Load axiom: nat_ico_zero_eq_range [introduce_axiom]
  Step 2: Load axiom: complex_norm_natcast_cpow_le_norm_natcast_cpow_iff [introduce_axiom]
  Step 3: Load axiom: int_emod_two_eq_zero_or_one [introduce_axiom]
  Step 4: Load axiom: lorentzgroup_isproper_id [introduce_axiom]
  Step 5: Load axiom: nat_pair_lt_max_add_one_sq [introduce_axiom]
  Step 6: Load axiom: complex_conj_ofnat [introduce_axiom]
  Step 7: Load axiom: int_neg_nat_succ [introduce_axiom]
  Step 8: Load axiom: int_modulus_add_modeq_iff [introduce_axiom]
  Step 9: Suffix: X²=Y² for take-root [rearrange_equation]
  Step 10: Take positive square root (E ≥ 0, mc² ≥ 0) [take_positive_root]
-/

/-- Auto-derived theorem (chain length 10). -/
theorem submit_gen0_0
    (Finset.Ico Finset.range m : ℝ)
    (hm : 0 ≤ m)
    (h_nat_ico_zero_eq_range : (Finset.Ico 0) = Finset.range)
    (h_complex_norm_natcast_cpow_le_norm_natcast_cpow_iff : (∀ (n : Nat), (1 < n → (∀ (w : Complex), (∀ (z : Complex), ((Norm.norm ((Nat.cast n) ^ w)) ≤ (Norm.norm ((Nat.cast n) ^ z)) ↔ (Complex.re w) ≤ (Complex.re z)))))))
    (h_int_emod_two_eq_zero_or_one : (∀ (n : Int), (((HMod.hMod n) 2) = 0 ∨ ((HMod.hMod n) 2) = 1)))
    (h_lorentzgroup_isproper_id : (∀ (d : Nat), (LorentzGroup.IsProper 1)))
    (h_nat_pair_lt_max_add_one_sq : (∀ (m : Nat), (∀ (n : Nat), ((Nat.pair m) n) < ((((Max.max m) n) + 1) ^ 2))))
    (h_complex_conj_ofnat : (∀ (n : Nat), (∀ (inst.__.Mathlib.Data.Complex.Basic.2726087626._hygCtx._hyg.5 : (Nat.AtLeastTwo n)), ((DFunLike.coe (starRingEnd Complex)) (OfNat.ofNat n)) = (OfNat.ofNat n))))
    (h_int_neg_nat_succ : (∀ (n : Nat), (-(Nat.cast (Nat.succ n))) = (Int.pred (-(Nat.cast n)))))
    (h_int_modulus_add_modeq_iff : (∀ (n : Int), (∀ (a : Int), (∀ (b : Int), ((((Int.ModEq n) (n + a)) b) ↔ (((Int.ModEq n) a) b))))))
    : (m * c) = (c ^ 2) := by
  have h_em : ((m * c) ^ 2) = ((c ^ 2) ^ 2) := by
    first
      | (nlinarith [hm, h_nat_ico_zero_eq_range, h_complex_norm_natcast_cpow_le_norm_natcast_cpow_iff, h_int_emod_two_eq_zero_or_one, h_lorentzgroup_isproper_id, h_nat_pair_lt_max_add_one_sq, h_complex_conj_ofnat, h_int_neg_nat_succ, h_int_modulus_add_modeq_iff, sq_nonneg ((m * c)), sq_nonneg ((c ^ 2))])
      | (polyrith)
      | (linear_combination 0)
  have hmc : 0 ≤ (c ^ 2) := by positivity
  have h_sqrt := congr_arg Real.sqrt h_em
  rwa [Real.sqrt_sq (by nlinarith [hm, h_nat_ico_zero_eq_range, h_complex_norm_natcast_cpow_le_norm_natcast_cpow_iff, h_int_emod_two_eq_zero_or_one, h_lorentzgroup_isproper_id, h_nat_pair_lt_max_add_one_sq, h_complex_conj_ofnat, h_int_neg_nat_succ, h_int_modulus_add_modeq_iff, sq_nonneg ((m * c)), sq_nonneg ((c ^ 2))] : 0 ≤ (m * c)), Real.sqrt_sq hmc] at h_sqrt

end PhysicsGenerator.Derived
