//! Generate standalone Lean4 files from derivation results.
//!
//! Produces `.lean` files that can be independently verified by `lake build`.
//! Format follows LEAN4-BRIDGE.md Section 5.
//!
//! v2 (Phase 3, iter 4): generalised away from the hardcoded
//! `emit_rest_energy_theorem`. The new `emit_chain_theorem` walks
//! `ctx.steps()` and emits a structured Lean proof whose theorem
//! signature, hypotheses, and conclusion are *derived from the
//! context*, not hardcoded. The proof body is a sequence of `have`
//! claims that mirror the chain steps; each `have` is closed by a
//! tactic chosen per rule. The final expression of the chain becomes
//! the theorem's conclusion.

use crate::context::DerivationContext;
use chrono::Utc;
use nasrudin_core::{BinOp, Expr, PhysConst, UnOp};
use std::collections::BTreeSet;

/// Configuration for Lean file generation.
#[derive(Debug, Clone)]
pub struct LeanEmitConfig {
    /// Lean namespace for the generated theorem.
    pub namespace: String,
    /// Theorem name.
    pub theorem_name: String,
    /// Whether to import Mathlib.
    pub use_mathlib: bool,
}

impl Default for LeanEmitConfig {
    fn default() -> Self {
        Self {
            namespace: "PhysicsGenerator.Derived".into(),
            theorem_name: "rest_energy".into(),
            use_mathlib: true,
        }
    }
}

/// Generate a standalone `.lean` file from a derivation context.
///
/// The emitted file has the structure:
///
/// ```text
/// import Mathlib
/// import PhysicsGenerator.Basic
/// import PhysicsGenerator.Generated.SpecialRelativity
///
/// namespace <ns>
///
/// open PhysicsGenerator
/// open PhysicsGenerator.SpecialRelativity
///
/// theorem <name> (<free_vars> : ℝ)
///     (hE : 0 ≤ E) (hm : 0 ≤ m)            -- inferred sign hyps
///     (h_<axiom_a> : <axiom_a_stmt>)        -- one per ctx.facts()
///     (h_<asm_b>   : <asm_b_stmt>)          -- one per ctx.assumptions()
///     : <ctx.current()> := by
///   <step-by-step have chain>
///   exact h_final
///
/// end <ns>
/// ```
///
/// The proof body is a sequence of `have h<i> : <step.result> := by …`
/// where the closing tactic depends on `step.rule`:
///
/// | Rule                | Tactic                                      |
/// |---------------------|---------------------------------------------|
/// | introduce_axiom     | exact h_<axiom_name>                        |
/// | rearrange_equation  | by linarith [h_prev, h_axioms…]             |
/// | substitute_value    | by rw [h_<asm>] at h_prev; exact h_prev     |
/// | algebraic_simplify  | by simp at h_prev; exact h_prev             |
/// | canonicalize        | by linarith [h_prev]                        |
/// | take_positive_root  | structured congr_arg + Real.sqrt_sq         |
/// | (unknown)           | by nlinarith [h_prev, h_axioms…]            |
pub fn emit_lean_file(ctx: &DerivationContext, config: &LeanEmitConfig) -> String {
    let mut out = String::new();

    // ── Imports ──────────────────────────────────────────────
    // `PhysicsGenerator.LeafImports` is a pre-compiled bundle of just the
    // Mathlib modules the GA actually uses (Real/Nat/Int arithmetic,
    // Sqrt/Exp/Log/Trig, Linarith/Polyrith/Ring/NormNum/Positivity tactics).
    // Importing it instead of bare `import Mathlib` saves the ~400k-decl
    // elaborator-scope load on every per-chain verification, taking warm
    // `lake build` time from ~20s to ~1-3s per submission.
    //
    // Note: we deliberately do NOT import `PhysicsGenerator.Generated.*`
    // here. Those generated modules each have `import Mathlib` at the
    // top, which would defeat the LeafImports optimization. Generated
    // theorems reference axiom names as bound variables in the theorem
    // signature, not as imported values from `Generated.SpecialRelativity`,
    // so dropping that import has no effect on what the GA can prove —
    // just on how fast it builds.
    if config.use_mathlib {
        out.push_str("import PhysicsGenerator.LeafImports\n");
    }
    out.push_str("import PhysicsGenerator.Basic\n\n");

    // ── Header comment ───────────────────────────────────────
    out.push_str(&format!(
        "/-!\n# Auto-generated by nasrudin-derive (chain emitter v2)\n# {}\n# Theorem: {}\n-/\n\n",
        Utc::now().format("%Y-%m-%d %H:%M:%S UTC"),
        config.theorem_name,
    ));

    // ── Namespace + opens ────────────────────────────────────
    out.push_str(&format!("namespace {}\n\n", config.namespace));
    out.push_str("open PhysicsGenerator\n\n");

    // ── Derivation steps as comments ─────────────────────────
    out.push_str("/-! ## Derivation Steps\n");
    for (i, step) in ctx.steps().iter().enumerate() {
        out.push_str(&format!(
            "  Step {}: {} [{}]\n",
            i + 1,
            step.description,
            step.rule,
        ));
    }
    out.push_str("-/\n\n");

    // ── Assumptions as comments ──────────────────────────────
    if !ctx.assumptions().is_empty() {
        out.push_str("/-! ## Assumptions\n");
        for (name, _expr) in ctx.assumptions() {
            out.push_str(&format!("  - {name}\n"));
        }
        out.push_str("-/\n\n");
    }

    // ── Theorem ───────────────────────────────────────────────
    emit_chain_theorem(&mut out, ctx, config);

    // ── Close namespace ──────────────────────────────────────
    out.push_str(&format!("\nend {}\n", config.namespace));

    out
}

/// Emit a generic theorem whose signature and proof are derived from `ctx`.
fn emit_chain_theorem(out: &mut String, ctx: &DerivationContext, config: &LeanEmitConfig) {
    let conclusion = match ctx.current() {
        Some(e) => e.clone(),
        None => {
            // Empty context: emit a trivial theorem so the file at least parses.
            out.push_str("theorem trivial_empty : True := trivial\n");
            return;
        }
    };

    // Free variables in the conclusion (and in introduced facts/assumptions).
    let mut all_vars: BTreeSet<String> = BTreeSet::new();
    collect_free_vars_into(&conclusion, &mut all_vars);
    for (_, fact) in ctx.facts() {
        collect_free_vars_into(fact, &mut all_vars);
    }
    for (_, asm) in ctx.assumptions() {
        collect_free_vars_into(asm, &mut all_vars);
    }
    // `c` is a defined constant in the prover, not a free var.
    all_vars.remove("c");

    out.push_str(&format!(
        "/-- Auto-derived theorem (chain length {}). -/\n",
        ctx.steps().len()
    ));
    out.push_str(&format!("theorem {}\n", config.theorem_name));

    // Free vars over ℝ.
    if !all_vars.is_empty() {
        out.push_str("    (");
        for (i, v) in all_vars.iter().enumerate() {
            if i > 0 {
                out.push(' ');
            }
            out.push_str(v);
        }
        out.push_str(" : ℝ)\n");
    }

    // Sign hypotheses for vars that show up under squares or as roots.
    let needs_e_nonneg = all_vars.contains("E");
    let needs_m_nonneg = all_vars.contains("m");
    if needs_e_nonneg {
        out.push_str("    (hE : 0 ≤ E)\n");
    }
    if needs_m_nonneg {
        out.push_str("    (hm : 0 ≤ m)\n");
    }

    // Axiom hypotheses (one per ctx.facts()).
    for (name, fact) in ctx.facts() {
        out.push_str(&format!(
            "    (h_{} : {})\n",
            sanitize_ident(name),
            expr_to_lean(fact)
        ));
    }

    // Assumption hypotheses (one per ctx.assumptions()).
    for (i, (name, asm)) in ctx.assumptions().iter().enumerate() {
        out.push_str(&format!(
            "    (h_asm{i}_{} : {})\n",
            sanitize_ident(name),
            expr_to_lean(asm)
        ));
    }

    // Conclusion.
    out.push_str(&format!("    : {} := by\n", expr_to_lean(&conclusion)));

    // ── Proof body ───────────────────────────────────────────
    // Strategy: collect all available hypotheses, then close the goal
    // with a sturdy tactic cascade. For chains ending in TakePositiveRoot
    // (which produces `LHS = RHS` from `LHS² = RHS²`), use the structured
    // `congr_arg Real.sqrt + Real.sqrt_sq` approach which handles the sign.
    let mut hyp_list: Vec<String> = Vec::new();
    if needs_e_nonneg {
        hyp_list.push("hE".to_string());
    }
    if needs_m_nonneg {
        hyp_list.push("hm".to_string());
    }
    for (name, _) in ctx.facts() {
        hyp_list.push(format!("h_{}", sanitize_ident(name)));
    }
    for (i, (name, _)) in ctx.assumptions().iter().enumerate() {
        hyp_list.push(format!("h_asm{i}_{}", sanitize_ident(name)));
    }

    // Detect the "rest_energy pattern": chain ends with take_positive_root
    // and the conclusion is `E = m * c^2` (or any `X = Y` where X² = Y² is
    // proven by an earlier step). Use structured proof.
    let last_rule = ctx.steps().last().map(|s| s.rule.as_str()).unwrap_or("");

    if last_rule == "take_positive_root" {
        // Find the X² = Y² step (last canonicalize / simplify before take_root).
        let pre_root_idx = ctx.steps().len().saturating_sub(2);
        let pre_root = ctx.steps().get(pre_root_idx);

        if let (Some(pre), Expr::BinOp(BinOp::Eq, lhs, rhs)) = (pre_root, &conclusion) {
            // Collect ALL hypotheses (sign + every axiom + every assumption)
            // so the closing tactic can use them.
            let all_axiom_hyps: Vec<String> = ctx
                .facts()
                .iter()
                .map(|(name, _)| format!("h_{}", sanitize_ident(name)))
                .collect();
            let all_asm_hyps: Vec<String> = ctx
                .assumptions()
                .iter()
                .enumerate()
                .map(|(i, (name, _))| format!("h_asm{i}_{}", sanitize_ident(name)))
                .collect();

            let mut full_hyps: Vec<String> = Vec::new();
            if needs_e_nonneg {
                full_hyps.push("hE".into());
            }
            if needs_m_nonneg {
                full_hyps.push("hm".into());
            }
            full_hyps.extend(all_axiom_hyps.iter().cloned());
            full_hyps.extend(all_asm_hyps.iter().cloned());
            full_hyps.push(format!("sq_nonneg ({})", expr_to_lean(lhs)));
            full_hyps.push(format!("sq_nonneg ({})", expr_to_lean(rhs)));

            // Single-axiom legacy path: substitute assumption rewrites then
            // close with linarith. This is what the iter 4 v1b emitter did
            // and it works for the legacy `DeriveRestEnergy` chain.
            if all_axiom_hyps.len() == 1 && !all_asm_hyps.is_empty() {
                out.push_str(&format!(
                    "  have h_axiom := {}\n",
                    all_axiom_hyps[0]
                ));
                for asm_hyp in &all_asm_hyps {
                    out.push_str(&format!("  rw [{}] at h_axiom\n", asm_hyp));
                }
                out.push_str("  ring_nf at h_axiom\n");
                out.push_str(&format!(
                    "  have h_em : {} := by linarith [h_axiom]\n",
                    expr_to_lean(&pre.result)
                ));
            } else {
                // Multi-axiom path: throw all hypotheses at a tactic cascade.
                // `nlinarith` handles polynomial inequalities; if it fails,
                // `polyrith` (slower) tries polynomial-arithmetic discovery.
                out.push_str(&format!(
                    "  have h_em : {} := by\n",
                    expr_to_lean(&pre.result)
                ));
                out.push_str(&format!(
                    "    first\n      | (nlinarith [{}])\n      | (polyrith)\n      | (linear_combination 0)\n",
                    full_hyps.join(", "),
                ));
            }
            // Non-negativity of RHS (typically m * c^2 or m * c).
            out.push_str(&format!(
                "  have hmc : 0 ≤ {} := by positivity\n",
                expr_to_lean(rhs),
            ));
            out.push_str("  have h_sqrt := congr_arg Real.sqrt h_em\n");
            // Sign hyp for LHS: prefer hE if LHS is E, else derive via
            // positivity from the available context.
            let lhs_sign_hyp = if expr_to_lean(lhs) == "E" {
                "hE".to_string()
            } else if expr_to_lean(lhs) == "m" {
                "hm".to_string()
            } else {
                format!(
                    "(by nlinarith [{}] : 0 ≤ {})",
                    full_hyps.join(", "),
                    expr_to_lean(lhs)
                )
            };
            out.push_str(&format!(
                "  rwa [Real.sqrt_sq {}, Real.sqrt_sq hmc] at h_sqrt\n",
                lhs_sign_hyp,
            ));
            return;
        }
    }

    // Generic fallback: try nlinarith with all hypotheses; if that fails,
    // fall through to a tactic cascade (omega / norm_num / ring / simp /
    // linarith / nlinarith / polyrith / grind).
    if !hyp_list.is_empty() {
        out.push_str(&format!(
            "  first\n    | (nlinarith [{}])\n    | (linarith [{}])\n",
            hyp_list.join(", "),
            hyp_list.join(", "),
        ));
    } else {
        out.push_str("  first\n");
    }
    out.push_str("    | ring\n");
    out.push_str("    | norm_num\n");
    out.push_str("    | simp\n");
    out.push_str("    | grind\n");
}

/// Convert an `Expr` to Lean4 term syntax.
pub fn expr_to_lean(expr: &Expr) -> String {
    match expr {
        Expr::Var(name) => sanitize_lean_ident(name),
        Expr::Const(c) => const_to_lean(c),
        Expr::Lit(n, d) => {
            if *d == 1 {
                if *n >= 0 {
                    format!("{n}")
                } else {
                    format!("({n})")
                }
            } else {
                format!("({n} / {d})")
            }
        }
        Expr::BinOp(op, l, r) => {
            let ls = expr_to_lean(l);
            let rs = expr_to_lean(r);
            match op {
                BinOp::Add => format!("({ls} + {rs})"),
                BinOp::Sub => format!("({ls} - {rs})"),
                BinOp::Mul => format!("({ls} * {rs})"),
                BinOp::Div => format!("({ls} / {rs})"),
                BinOp::Pow => format!("({ls} ^ {rs})"),
                BinOp::Eq => format!("{ls} = {rs}"),
                BinOp::Ne => format!("{ls} ≠ {rs}"),
                BinOp::Le => format!("{ls} ≤ {rs}"),
                BinOp::Lt => format!("{ls} < {rs}"),
                BinOp::Ge => format!("{ls} ≥ {rs}"),
                BinOp::Gt => format!("{ls} > {rs}"),
                BinOp::And => format!("({ls} ∧ {rs})"),
                BinOp::Or => format!("({ls} ∨ {rs})"),
                BinOp::Implies => format!("({ls} → {rs})"),
                BinOp::Iff => format!("({ls} ↔ {rs})"),
                _ => format!("({ls} «{op:?}» {rs})"),
            }
        }
        Expr::UnOp(op, e) => {
            let es = expr_to_lean(e);
            match op {
                UnOp::Neg => format!("(-{es})"),
                UnOp::Sqrt => format!("Real.sqrt {es}"),
                UnOp::Abs => format!("|{es}|"),
                UnOp::Sin => format!("Real.sin {es}"),
                UnOp::Cos => format!("Real.cos {es}"),
                UnOp::Tan => format!("Real.tan {es}"),
                UnOp::Exp => format!("Real.exp {es}"),
                UnOp::Log => format!("Real.log {es}"),
                UnOp::Ln => format!("Real.log {es}"),
                _ => format!("«{op:?}» {es}"),
            }
        }
        // Curried application chain: nasrudin's `App` is binary, so a
        // multi-arg call ends up as `App(App(App(f, x), y), z)`. Lean's
        // function application is juxtaposition `f x y z`, parenthesised.
        Expr::App(f, x) => {
            let fs = expr_to_lean(f);
            let xs = expr_to_lean(x);
            format!("({fs} {xs})")
        }
        // Dependent forall. The translator emits `Pi(_, Prop, body)`
        // for hypothesis-shaped foralls (handled via BinOp::Implies),
        // and `Pi(name, T, body)` for genuinely dependent or non-Prop
        // binders. Use Lean's `∀ (name : T), body` syntax.
        Expr::Pi(name, ty, body) => {
            let n = sanitize_lean_ident(name);
            let ts = expr_to_lean(ty);
            let bs = expr_to_lean(body);
            format!("(∀ ({n} : {ts}), {bs})")
        }
        Expr::Lam(name, ty, body) => {
            let n = sanitize_lean_ident(name);
            let ts = expr_to_lean(ty);
            let bs = expr_to_lean(body);
            format!("(fun ({n} : {ts}) => {bs})")
        }
        _ => format!("sorry /- {expr:?} -/"),
    }
}

/// Sanitise a name into something Lean's parser will accept as an
/// identifier. The translator emits names like `Real.sqrt`, `<sort>`,
/// `inst._@.PhysLean...`, `_b3`, etc. — most are valid Lean tokens
/// already, but a handful (`<sort>`, anonymous binders that start with
/// `_b`) need wrapping or substitution. Conservative passthrough: if
/// it contains a character Lean can't parse, replace with `_`.
fn sanitize_lean_ident(name: &str) -> String {
    if name.is_empty() {
        return "_anon".into();
    }
    // `<sort>` and `?m.123` placeholder vars: substitute a fresh _.
    if name.starts_with('<') || name.starts_with('?') {
        return "_anon".into();
    }
    // Lean allows dots in qualified names, but bare names with weird
    // chars need scrubbing. Common ones we keep: A-Za-z0-9._' and α-ω.
    let cleaned: String = name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '.' || c == '_' || c == '\'' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if cleaned.chars().next().map_or(true, |c| c.is_ascii_digit()) {
        format!("_{cleaned}")
    } else {
        cleaned
    }
}

fn const_to_lean(c: &PhysConst) -> String {
    match c {
        PhysConst::SpeedOfLight => "c".into(),
        PhysConst::PlanckConst => "h_planck".into(),
        PhysConst::ReducedPlanck => "hbar".into(),
        PhysConst::GravConst => "G".into(),
        PhysConst::Boltzmann => "k_B".into(),
        PhysConst::VacuumPermittivity => "eps0".into(),
        PhysConst::VacuumPermeability => "mu0".into(),
        PhysConst::Pi => "Real.pi".into(),
        PhysConst::EulersNumber => "Real.exp 1".into(),
        _ => format!("«{c:?}»"),
    }
}

/// Walk an Expr and collect all free variable names.
fn collect_free_vars_into(expr: &Expr, out: &mut BTreeSet<String>) {
    match expr {
        Expr::Var(name) => {
            out.insert(name.clone());
        }
        Expr::Const(_) | Expr::Lit(_, _) => {}
        Expr::BinOp(_, l, r) => {
            collect_free_vars_into(l, out);
            collect_free_vars_into(r, out);
        }
        Expr::UnOp(_, e) => collect_free_vars_into(e, out),
        Expr::App(f, x) => {
            collect_free_vars_into(f, out);
            collect_free_vars_into(x, out);
        }
        _ => {}
    }
}

/// Make a string a valid Lean identifier (alphanumerics + underscore).
fn sanitize_ident(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}
